language: go

go:
- master
- 1.x
- 1.9.x
- 1.10.x

matrix:
  allow_failures:
  - go: master
  fast_finish: true

sudo: false

before_install:
- export DEP_VERSION=0.4.1
- export GO_TEST_COVERAGE_FILENAME='coverage.out'

- wget -q -O dep https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
- chmod +x dep && mv dep "${GOPATH}"/bin
- go get github.com/mattn/goveralls

- make tools

install:
- make generate

script:
- make test-with-coverage-profile ARGS='-timeout=1s'

after_success:
- goveralls -service=travis-ci -coverprofile="${GO_TEST_COVERAGE_FILENAME}"
- echo $TRAVIS_GO_VERSION ":" $TRAVIS_TAG
- if [[ $TRAVIS_GO_VERSION == 1.10* ]] && [ -n "$TRAVIS_TAG" ]; then curl -sL https://git.io/goreleaser | bash; fi

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3f7a9d417a5fc07428ef
    on_success: change
    on_failure: always
    on_start:   never
